#!/bin/sh
if [ $# -ne 2 ]; then
	echo "Syntax: $0 <vol> <hlq>" >&2
	echo "  Set up alias <hlq> on user catalog for volume <vol>" >&2
	exit 4
fi

vol=$(echo ${1} | tr '[:lower:]' '[:upper:]')
hlq=$(echo ${2} | tr '[:lower:]' '[:upper:]')
sysname=`sysvar SYSNAME`
user="CATALOG.${sysname}USER.${vol}.CAT"

master="CATALOG.${sysname}MSTR.CAT"

echo "
  DELETE (${hlq}) ALIAS CAT(${master})
  SET MAXCC=0
  DEF ALIAS (NAME(${hlq}) REL(${user})) -
            CAT(${master})
" | mvscmdauth --pgm=IDCAMS --sysin=stdin --sysprint=stdout
rc=$?

exit $rc
